### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by aleeper** [cbraley/threadpool#1]
I didn't find a license file in this repo, or any license info in the source files. Does this have a permissive license such as BSD or MIT? I'd love to use this in my project, but want to be clear on the licensing requirements before I do so.

**Comment by cbraley** [comment]
I just saw this long after you posted it! I don't check my github often. 

I've added an MIT license for this repo. I don't know much about licensing - I chose MIT since AFAIK it is permissive as possible.
